### PR TITLE
add hashtables and judy arrays insert and lookup

### PR DESCRIPTION
**Pull request by jrraymond**
I'll add hashtables and judy arrays to the rest of the time and space benchmarks when i get the chance and if you like what I did so fat

### CODE REVIEW

**Comment by chrisdone** [comment]
Cool. I think this is measuring the creation of the hash table as well as the lookup/insert. But it's a good start, merging!

**Comment by chrisdone** [comment]
I was hoping someone would contribute mutable hash tables. Thanks!

**Comment by jrraymond** [comment]
I'll fix that and add the rest of the benchmarks when I get the chance. I also think there is Data.HashTable from base.

**Comment by chrisdone** [comment]
Judy's results indicate a zig-zag, I'm not sure whether that's expected. Perhaps its uses buckets.

https://github.com/haskell-perf/dictionaries#io-lookup-int-randomized

**Comment by jrraymond** [comment]
[Judy arrays are 256-ary tries,](http://judy.sourceforge.net/doc/10minutes.htm) I won't pretend to know how they work. Also, the don't the Map benchmarks count the create of the empty Map too? or is the cost considered negligible enough that it doesn't matter.

**Comment by chrisdone** [comment]
I think I was wrong about the IO ones allocating the map too late. It's fine, but I did update both the pure and IO to always get a _hit_ with a key that exists, I think we might have been getting a miss. The cost of a miss is a separately interesting thing to measure.

**Comment by jrraymond** [comment]
The insert IO definitely allocate the map, the lookup IO allocate the map initially. I was reading the criterion docs and it says [env is evaulated to normal form before being passed to the benchmarks](https://hackage.haskell.org/package/criterion-1.1.4.0/docs/Criterion-Main.html#g:6). Does this mean the `force` is not needed in any of the `env` setup?

**Comment by chrisdone** [comment]
> Does this mean the force is not needed in any of the env setup?

I think so.

**Pull request merged**
